version: '3'
services:
  app:
    container_name: userapi
    image: userapi
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userapi
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:12
    container_name: db
    ports:
      - 5000:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=userapi
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - sample_db:/var/lib/postgresql/data
    restart: always
volumes:
  sample_db: